// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smgujwjtucsypnpahvhk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtZ3Vqd2p0dWNzeXBucGFodmhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNjQ5MTcsImV4cCI6MjA2NTY0MDkxN30.Rb7z3uSHgxnRyMdabVa0jz74PRkTQeY0OyWh_TljhvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);